server = "https://mds-dev.micfong.space"
recipients = [
  "age1pq19tntgucntf9wcyzz2x0fhjmh4fe8ac3enkm4djne2k80vjzxrfsv2wpgzeguj9jmg7fjujt44ktfsxzntm7kv6uhuxgjaka97xrthfuny08mrzjflsz3gqvs2zs8h98jejca2dvk6c3fhsrjwtdvcn59xk66yqn679jyavq27v4q036vek395vekc0zmg4mw6cpcmvxzpkcmkg5q74jp4ugpflngwl7n59c0zrg5lyxdw4yp093fxhhcqyxsyg7puznsu64reqgnwxm2nkee2xs7wggelsj5avt50rwyhwa70g9gwqcxu593sfszarh2wfnqr9k98262flrkwk6r6yhytl4x4y3adyvy9wkyuefszwef2w8wv3ag5e0qp0w2m3mvcwwmdp8w285c93cn45f3csdkq8c84pl3ysgu7pfhp73eev58kxs94xnq0zuwhq42tycrxprk3j5sg6fnkl9tmwnmgyxpg7vnt3z2gejxg3qz6xzgehxpaerzgtsuq0kk49nzev5depez00qy82cfstdf5dtvycee4krcyd2xzxnnjf9sj7mxz45jeqvkk8a8ux4ykpcc9yh3dd8622getgnyr3qf4nr60js2ku4tk32ufeajumqtgkkgr9y4x5eflsyrvmq5hh5g3rejkn5y8zjf06sdmgznmd4k3ml08t09sj95rmqpuu78wtn9s32yt036qdrnxsar67ezcy8ed07y0tkwhw32heqm3qgkpt3hpqsszyxwdva8xgufz9x8uv5t2r7ygu40vckd56y682tgytw3v3kz5f6ufwm0hrzuwe53uhf8zafuwc0y74dnfpz6r0sh8qkzpywu9xtdclr0tgfd5343jdq2nf7mykn2gl8ga29sknt22r6rk0euzaqqgkxkf64khccqjf085a2l3nhy9s3xygcqr2rcqd85cmvhk9cf3ywsyk9njtdt7l2ks0tfvkk6hz3zq9ndy7dhem7vpdc30nt34v8yqd7q30n8yhdr8judwz2ypxcg55xrnqphy6fk3edfzakdck7lxq6h4f966y52e7jh5a6p7qhnnjjhpccmurzk2e8lw2jvx8yrzqrn2p4mgrgn5ewe0f839pyl7zadcwmxflxq2j9yfy2qe9w6u7fvsqs6rnx5cfj0qlu60sc6l5dr6zrj7c8uxg84v5ruuu0u4dtchcyx0w2tdnhezrtszxkq93rt0cp9f5jkg4qn8qd8mjehj3ycayeceq4ur94qgkmqqap7nxyekwvcgeezyqptchsacus7jefjamz5ee4e234e4re6st8jd3zck0sxy7cvysyyw2hhgqp9hpryvaz4w66qzh5g2d2xvgfvy2duecq6s7ecjzvpg688qzg8vzs7c5cxsqnykcuun23vm0zwhn9786f4k4txvvvrwr486arjns2dfuuhjmqngf0axddfz7s33czx674627kftnx7jcy72mx5g3amsn368fmqn077scyttvdh5y5wwskxj0gjhmf00pt8av6na3cz7ckzscx99h7svy6fn8x28zjw93u8e8nsynmk5ne0f3xl8kgecjm9kazxwj9cq2vt5s97jjmmhqrxkgm2dqswymautftsg728hgux44vgj4stv8t7ezgl4v40kfvenw7kgdygrduzsxs65fvn8h52gqd6s5eue9wrk6g2jx2l9r3vuzuqrp79xvasnv0srwa325qmywas4esj000kxck6tjrwgwdt7an936dznwnt4n8xyvxpwfsmftxqdvnrhnsq847j0xf4qsdg6k0rnsxrq8vpkksrww2uuzg9hzq522n5yccakauw09sl0ehg6ceccwwxyl2pqaslnmtmpa66rdt9e86hyp8vyxdanxj90av8glr8ygclfumxd3q653lctut7juk9h8y48stnur0s06hatcrlveul",
  "age1pq1az9tl7gh3phg4zkrz26amkevyrq8krve0s9zezy9ndclqpqjjdmxxc74ykrnjgxcg9fk3928h7fcpkvp3w2hkxuecgafsd5w8fgydazhrh3xwd7e2qrhtez59a46w5xjt86vgh8948yz95dtudc2w2gzgj6lxhwx9z65yafzqlqq0l6r3f9ydvtsqh9j6ft30rs6htjrtuasdz4mtp93sxnnd32jf2zvn03spx7dp34ss9a6g62vzt4fzzeq9tts6936vy7w9pp5mwjrgsu7dp8tsgzqn9924kwvmdujxa7dhsnlxsm5fxszwwnu5fzpjqln8dd6uuz7pz580sdefs6jf2wd5s650s2h83my86axdelpx4fd5r2c6k9vtzvvewpfmt6njjndjdrts8xxjz4epl3tvywsk2fp98p4q7pdckv82pnrmc7ud4kkq93m7ul8uvye3hje488fze7wq49pjvp5se7w9g584zdmz85mt97yc4524pp5w9g2j56qnk25s9gjv70w3ygcjy9vq3xe2zefcrrc08p6sygehrakz2tfslzryqxw5gvrx43tfgnr8trq5z2zvvt38pxwr27flaje57shxmqp2v2u0fwmce65zm9gswzgswlvyry8zfydjhzwt0sfgqxj20g0kxlwyulcf6n2aa7gt3cf9y0rjkejht9jzertnc6efdmj37w7g52t7qyf0qsnqv5zz7ppgzcf9ykdghqvms5kz5vnmedn3aupwg5rdqs7f0xd9ndyjqw8cppvk2x65a6fsuazdupz6t86vftv2v0t3vuxspyjckvjcrjm3ggnttzpgpk2jq9xrccys92psunmp8j5zp8qkxejyygju308gqv92ya6vgrpduaysqnfrw32kpc2nzhtkelgkfnheryemzq4esct89yddqqgs4zhs3ssllkey6uevc7ju22f69m5gaff9ekzcscwc2ap8vtsq4rv5cd855tcrc4nnq4qxgx8landq4v5mqe8xyy8pf8cw6jveygjp4zv6fq6gxuvy75qcfrws2ea2px8253uftu2g5q7u98m65a3s2azq7u3hlxn394ayp7knz39u45p6rz3svnejd9x6g360hrfas2xt9zf0ax9w5dels0zzfz3pt7ryky6xfp30ga2jqh6m9mt03yprn0xk5ye2f6paszp5ksrwnx2shkmr4fsks8kess2xz5tsx234m33y2vsz7rxg4nsfft22hfqw736yx55v23v5p9hg5c2409gk8tgcc5mjmtktnpd0wjf23qymhzssy83grzssey3dfvnuygfw9my3u9e824w42yawkcme9af84ftqya8n098yjv8wfp6ufnhxrg6cc6tzdczs42h396zw6mskg894yqt26ypexq8fj4utg3q7djfdf6nhf5uqz7v5g79sdszs50g8zlxq73c9nqj7sam9vpkg7zjxrwsy5acy67xwwfume4fdqjsvh7zzw27ryctjdtyg9af5vjj0z7mwr5vf30hppyw0w6jwlpkkqedye6ujxqah7yz5vazggw64vt08y9frsd7x53g5npn0fs4yk0x0q6kssdcyyj4549crkyqxhu8rq9tkjsus3vuqa536wt2wrn232lk770gj43hqh9z757h3pp4kdwkfq8l4q7dr9g6azxfyxjg9txrvrp93qtpz06y3xtn8p7qck2prwxkd96em7wrh6azrmww2vh2nj936hppe3uugnzzy93m4y2h67dt5zr847jcm84r8g793y6du27r9gy95ymv3akqhrc0vjyeadxg3apuhm6slxhpny4nzxqfcmp8kjkhvxfm9hndxj8sd23qp826tyc7hxfcav9x7sy86kqyryuu43pw42qzk9p5gwnmtpxjlryn88ery8s2v9gvj9jku7qtjfn3575vvy0nltvu",
]
entries = [
  "part-ia/analysis-i/main.typ",
  "part-ia/differential-equations/main.typ",
  "part-ia/dynamics-and-relativity/main.typ",
  "part-ia/groups/main.typ",
  "part-ia/numbers-and-sets/main.typ",
  "part-ia/probability/main.typ",
  "part-ia/vectors-and-matrices/main.typ",
  "part-ib/optimisation/main.typ",
  "part-ib/variational-principles/main.typ",
]

[[series]]
entry = "part-ia/series.typ"
volumes = [
  "part-ia/groups/main.typ",
  "part-ia/vectors-and-matrices/main.typ",
  "part-ia/numbers-and-sets/main.typ",
  "part-ia/differential-equations/main.typ",
  "part-ia/analysis-i/main.typ",
  "part-ia/dynamics-and-relativity/main.typ",
]

[typst]
args = ["--root", ".", "--font-path", "fonts", "--ignore-system-fonts"]
creation-timestamp = "git-deps"

[renditions]
canonical = "light-sans"
all = ["light-sans", "dark-sans", "light-serif", "dark-serif"]
output = "build/{slug}.{theme}.{font}.pdf"

[renditions.inputs]
light-sans = { theme = "light", font = "sans" }
dark-sans = { theme = "dark", font = "sans" }
light-serif = { theme = "light", font = "serif" }
dark-serif = { theme = "dark", font = "serif" }

[digest]
fonts = "git-tracked"
